### ISSUE TITLE
Start on Windows 10: "No such file or directory".

### ISSUE THREAD

**Issue by ILugaro** [Ben-Ryder/Conqueror-of-Empires#8] opened 2020-02-22 20:59 UTC
root - ERROR - caught at main
Traceback (most recent call last):
  File "main.py", line 16, in <module>
  File "main.py", line 12, in main
  File "project\control\controller.py", line 38, in run
  File "project\control\controller.py", line 61, in run_newgame
  File "project\menus\newgame.py", line 82, in __init__
  File "project\menus\newgame.py", line 86, in run
  File "project\menus\newgame.py", line 150, in handle_events
  File "project\menus\newgame.py", line 96, in create_game
  File "project\game\new.py", line 11, in make
  File "project\data.py", line 9, in save
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Intel\\Desktop\\Conqueror-of-Empires-v1.0\\data\\\\saved\\sdg'

**Comment by ILugaro** [comment] 2020-02-22 21:05
![image](https://user-images.githubusercontent.com/32419700/75099228-d34b4600-55c7-11ea-89d3-d3724600f96f.png)

**Comment by ILugaro** [comment] 2020-02-22 21:07
When I created new gamers and click to "game". Programm is crash. Mayby it is problem with character escaping.

**Comment by ben-ryder** [comment] 2020-02-22 21:32
Hey,
I'm not able to replicate this my end, maybe because I'm running on Linux.
I did notice some extra path separators being added in the `paths.py` file so I have cleaned these and committed it to a new [GH-8_cleaning-paths](https://github.com/Ben-Ryder/Conqueror-of-Empires/tree/GH-8_cleaning-paths) branch. If you can checkout that branch and see if it solves your issue?
If so I'll get it merged into dev and then master asap

**Comment by Grimmys** [comment] 2020-02-29 00:42
Hello,
I tested the first release on Windows 10 too, and encountered the same bug.

Create empty folder `data/saved` solved it.

(I can't say if [GH-8_cleaning-paths](https://github.com/Ben-Ryder/Conqueror-of-Empires/tree/GH-8_cleaning-paths) branch solves the issue, because I don't know what you use to create the .exe file., however game started fine with python command line.)

**Comment by ben-ryder** [comment] 2020-03-01 11:29
Thanks for letting me know @Grimmys 

This is actually a duplicate of GH-3 which was fixed in the same way. I should of remembered!!
For that fix I just added a .gitingore to preserve the empty folder but I forgot that wouldn't fix it for the packaged program.

I'll add a check when the program starts to create that folder if it isn't there, which is probably how I should have done it to begin with. :smile:

**Comment by ben-ryder** [comment] 2020-03-01 12:33
I have now made the [v1.0.1](https://github.com/Ben-Ryder/Conqueror-of-Empires/releases/tag/v1.0.1) release which adds this fix to the code base.

However, I am having a bit of difficulty running [cx_Freeze](https://cx-freeze.readthedocs.io/en/latest/) to create the new executables right now so I'll keep this issue open till I can sort it out.
I'll also still merge the [GH-8_cleaning-paths](https://github.com/Ben-Ryder/Conqueror-of-Empires/tree/GH-8_cleaning-paths)  branch as even if it wasn't the actual fix it's worth having those changes.

**Closed as completed** 2021-09-02 20:59 UTC
Labels: bug
